#GWAS run using gcta64 (available here: https://cnsgenomics.com/software/gcta/#Download)

# Input files:
# pancreatitis_vs_control_phenotypes.txt - fid, iid, and phenotype
# pancreatitis_vs_control_discrete_covars.txt - fid, iid, sex, and smoking
# pancreatitis_vs_control_quantitative_covars.txt - fid, iid, age, current bmi and PCAs 1-10 (generated by gcta6)4
# NAPS2.grm generated by gcta64 from .bed, .bim, and .fam
# Individuals to exclude from analysis are in the file exclude.txt

gcta64 --mlma \
--bfile NAPS2 \
--grm NAPS2 \
--pheno pancreatitis_vs_control_phenotypes.txt \
--covar pancreatitis_vs_control_discrete_covars.txt \
--qcovar pancreatitis_vs_control_quantitative_covars.txt \
--out NAPS2_pancreatitis_vs_control_out \
--thread-num 10 \
--maf 0.01 \
--autosome \
--remove exclude.txt

